version: "3.8"

services:
  join-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    volumes:
      - db:/var/lib/mysql

  join-backend:
    image: join-backend
    restart: always
    environment:
      FRONTEND_URL: http://localhost:3000
      DATABASE_ENV: production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: join-db
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    ports:
      - "1337:1337"
    depends_on:
      - join-db

volumes:
  db:
