version: '3'

volumes:
  join-data:

services:
  frontend:
    build: ./frontend-sveltekit
    environment:
      VITE_BACKEND_URL: http://backend:1337
    ports: 
      - 3000:3000
    depends_on: 
      - backend

  backend:
    build: ./backend-strapi
    environment:
      FRONTEND_URL: http://localhost:3000
      DATABASE_ENV: production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./backend-strapi:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - join-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3001:80
    environment:
      - PMA_ARBITRARY=1